export * from "./CheckCode/CheckCode"
export * from "./Dashboard/Dashboard"
export * from "./ForgotPassword/ForgotPassword"
export * from "./Home/Home"
export * from "./Login/Login"
export * from "./Profile/Profile"
export * from "./Register/Register"
export * from "./NotFound/NotFound"